Repository UBandera/uchat, pull requests merged in 2020-07, with the labels that each got.

#9 sign_up request to db
  client/src/mx_send_data.c
  client/src/screens/test.c
  json/inc/cJSON.h
  json/inc/mx_json.h
  json/src/cJSON.c
  json/src/mx_json_parser.c
  server/Makefile
  server/inc/server.h
  server/src/mx_get_online_users.c
  server/src/mx_get_socket_by_user_id.c
  server/src/mx_send_data.c
  server/src/server.c
  server/src/sign_up_handler.c
Labels: WIP

#28 Contact managing
  client/inc/client.h
  client/src/mx_client.c
  client/src/mx_receive_data.c
  client/src/requests/add_contact_request.c
  client/src/requests/auth_request.c
  client/src/requests/contact_list_request.c
  client/src/requests/get_contact_request.c
  client/src/requests/mx_form_chat_data_request.c
  client/src/requests/mx_form_contact_list_request.c
  client/src/requests/mx_form_recovery_password_request.c
  client/src/requests/mx_form_send_message_request.c
  client/src/requests/mx_form_signout_request.c
  client/src/responses/add_contact_handler.c
  client/src/responses/contact_list_handler.c
  client/src/responses/contact_not_found_handler.c
  client/src/responses/get_contact_handler.c
  client/src/responses/mx_chat_data_response.c
  client/src/responses/mx_contact_list_response.c
  client/src/responses/mx_profile_data_response.c
  client/src/responses/mx_send_message_response.c
  client/src/responses/mx_sign_in_response.c
  client/src/responses/mx_sign_out_response.c
  client/src/responses/mx_sign_up_response.c
  client/src/responses/password_handler.c
  client/src/screens/auth/edit_redirection.c
  client/src/screens/auth/password_validation_window.c
  client/src/screens/auth/phone_entering_window.c
  client/src/screens/close_window_by_esc.c
  client/src/screens/glade/main.glade
  client/src/screens/main_window/add_contact_dialog.c
  client/src/screens/main_window/dialog.css
  client/src/screens/main_window/main_window.c
  client/src/screens/mx_application_init.c
  client/src/screens/mx_show_contact_in_ui.c
  json/inc/mx_json.h
  server/inc/server.h
  server/src/mx_db_init.c
  server/src/mx_get_user_id_by_phone.c
  server/src/requests/add_contact_handler.c
  server/src/requests/auth_request_handler.c
  server/src/requests/get_contact_handler.c
  server/src/requests/mx_get_contacts_list.c
  server/src/requests/password_request_handler.c
  server/src/server.c
Labels: WIP, bug

#41 Chat
  client/inc/client.h
  client/src/mx_receive_data.c
  client/src/requests/chat_history_request.c
  client/src/responses/add_contact_handler.c
  client/src/responses/chat_history_handler.c
  client/src/responses/contact_list_handler.c
  client/src/responses/get_contact_handler.c
  client/src/responses/get_message_handler.c
  client/src/responses/remove_contact_handler.c
  client/src/responses/send_message_handler.c
  client/src/screens/auth/notify_off.css
  client/src/screens/auth/notify_on.css
  client/src/screens/auth/password_validation_window.c
  client/src/screens/auth/phone_entering_window.c
  client/src/screens/auth/profile_setuping_window.c
  client/src/screens/close_widget_by_esc.c
  client/src/screens/main_window/chat_control.c
  client/src/screens/main_window/main_window.c
  client/src/screens/mx_show_contact_in_ui.c
  json/inc/mx_json.h
  server/inc/server.h
  server/src/mx_message_sheduler.c
  server/src/mx_setup_as_read.c
  server/src/requests/add_contact_handler.c
  server/src/requests/get_contact_handler.c
  server/src/requests/mx_get_message_history.c
Labels: bug
